[package]
name = "rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "riot"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.27.2"
rayon = "1.11.0"

clap = { version = "4.5.53", features = ["derive", "unstable-ext"] }
clap_complete = { version = "4.5.64", features = ["unstable-dynamic"] }
crossterm = "0.29"

toml = "0.9"
serde_json = "1.0"
serde = { version = "1.0.228", features = ["derive"] }

indexmap = { version = "2.12.1", features = ["serde"] }
shell-words = "1.1"
itertools = "0.14"
tempfile = "3.24"
sha2 = "0.10"
fancy-regex = "0.17.0"
